version: '3'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      # - /opt/data/mongo_home:/host_mnt/c/data/db
      - /opt/data/mongo_home:/data/db
    restart: always

  backend:
    # use make realize to build a new images of realize
    image: realize:${REALIZE_VERSION}
    hostname: backend
    ports:
      - "8080:8080"
      # - "8082:8082"
      # - "443:443"
    environment:
      - GO111MODULE=off
      # HTTP
      - HTTP_READ_TIMEOUT=${HTTP_READ_TIMEOUT}
      - HTTP_WRITE_TIMEOUT=${HTTP_WRITE_TIMEOUT}
      - HTTP_READ_HEADER_TIMEOUT=${HTTP_READ_HEADER_TIMEOUT}
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
      - PORT=${PORT}
      - HTTP_HOST=${HTTP_HOST}
      - HTTP_ALLOWED_ORIGINS=${HTTP_ALLOWED_ORIGINS}
      - HTTP_PORT=${HTTP_PORT}
      # DB
      - MONGODB_ADDRS=${MONGODB_ADDRS}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      # - MONGODB_USERNAME=${MONGODB_USERNAME}
      # - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_TIMEOUT=${MONGODB_TIMEOUT}
    volumes:
      - ../../.realize.yaml:/home/vnmquan/WORK/workspace/src/github.com/Januadrym/seennit/.realize.yaml
      - ../../main.go:/home/vnmquan/WORK/workspace/src/github.com/Januadrym/seennit/main.go
      - ../../go.mod:/home/vnmquan/WORK/workspace/src/github.com/Januadrym/seennit/go.mod
      - ../../go.sum:/home/vnmquan/WORK/workspace/src/github.com/Januadrym/seennit/go.sum
      - ../../internal:/home/vnmquan/WORK/workspace/src/github.com/Januadrym/seennit/internal
      - ../../configs:/home/vnmquan/WORK/workspace/src/github.com/Januadrym/seennit/configs
      - ../scripts:/home/vnmquan/WORK/workspace/src/github.com/Januadrym/seennit/deployment/scripts
    working_dir: /home/vnmquan/WORK/workspace/src/github.com/Januadrym/seennit
    # entrypoint: [ "sh", "-c", "./wait-for.sh mongodb:27017 --timeout=5 -- realize start" ]
    entrypoint: [ "realize start" ]
    depends_on:
      - mongodb
    restart: always