settings:
  legacy:
    force: false
    interval: 0s
server:
  open: false
  status: true
  host: ""
  port: 8082
schema:
- name: backend
  path: /home/vnmquan/WORK/workspace/src/github.com/seennit
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    - mod
    - sum
    paths:
    - /
    ignore:
      paths:
      - .git
      - vendor