gen:
  success:
    code: 1000
    status: 200
    message: "Success"
  not_found:
    code: 1001
    status: 404
    message: "Not found"
  timeout:
    code: 1002
    status: 504
    message: "Timeout"
  bad_request:
    code: 1003
    status: 400
    message: "Bad request"
  internal:
    code: 1004
    status: 500
    message: "Internal server error"
policy:
  unauthorized:
    code: 1100
    status: 401
    message: "You are not authorized to access this resource"
auth:
  invalid_user_password:
    code: 1200
    status: 401
    message: "Invalid email or password"
user:
  duplicated_email:
    code: 1300
    status: 400
    message: "Duplicated email"
  register_fail:
    code: 1300
    status: 400
    message: "Failed to register"
community:
  create_failed:
    code: 1600
    status: 500
    message: "Failed to create community"
  name_taken:
    code: 1600
    status: 400
    message: "Name taken"
  user_enrolled:
    code: 1700
    status: 400
    message: "User already enrolled"
  community_not_found:
      code: 1800
      status: 400
      message: "Community not found"
post:
  archived:
    code: 1900
    status: 400
    message: "Post archived, can no longer be updated"
  post_not_found:
    code: 1900
    status: 400
    message: "Post not found"
  